apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  ports:
  - name: "5006"
    port: 5006
    targetPort: 5006
  selector:
    io.kompose.service: auth
  type: LoadBalancer
status:
  loadBalancer: {}
