apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cache
    spec:
      containers:
      - args:
        - redis-server
        - --save
        - "20"
        - "1"
        - --loglevel
        - warning
        - --requirepass
        - eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        image: redis:6.2-alpine
        imagePullPolicy: ""
        name: cache
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: cache
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: cache
status: {}
