apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cache
  name: cache
spec:
  ports:
  - name: "6380"
    port: 6380
    targetPort: 6379
  selector:
    io.kompose.service: cache
  type: LoadBalancer
status:
  loadBalancer: {}
