apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: file
  name: file
spec:
  containers:
  - env:
    - name: FILE_SERVICE_PORT
      valueFrom:
        configMapKeyRef:
          key: FILE_SERVICE_PORT
          name: file-service--env
    - name: SERVICE
      value: file
    image: node:13.12.0-alpine
    name: file
    ports:
    - containerPort: 5007
    resources: {}
    volumeMounts:
    - mountPath: /app
      name: file-claim0
  restartPolicy: OnFailure
  volumes:
  - name: file-claim0
    persistentVolumeClaim:
      claimName: file-claim0
status: {}
