apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: file
  name: file
spec:
  ports:
  - name: "5007"
    port: 5007
    targetPort: 5007
  selector:
    io.kompose.service: file
  type: LoadBalancer
status:
  loadBalancer: {}
